// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type User struct {
	ID           uuid.UUID
	CreateAt     time.Time
	UpdateAt     time.Time
	Name         string
	UserName     string
	Password     string
	Role         string
	ApiKey       sql.NullString
	ParentUserID uuid.NullUUID
}
